#!/bin/bash
# init script for initializing blockchain-network

echo "INITv2 START"

docker rm -f mongodb
docker rm -f rest-server

~/fabric-tools/stopFabric.sh
~/fabric-tools/teardownFabric.sh

rm -rf $HOME/.composer

rm *.card
rm *.bna

# Starting the Fabric
~/fabric-tools/downloadFabric.sh
~/fabric-tools/startFabric.sh
~/fabric-tools/createPeerAdminCard.sh

# Deploying the business network
composer archive create -t dir -n .
composer runtime install --card PeerAdmin@hlfv1 --businessNetworkName blockchain-network
composer network start --card PeerAdmin@hlfv1 --networkAdmin admin --networkAdminEnrollSecret adminpw --archiveFile blockchain-network@0.0.1.bna --file blockchainadmin.card
composer card import --file blockchainadmin.card

echo "INITv2 END"

# cd ~/.composer/cards/admin@blockchain-network
# in conneciton.json change localhost to 172.17.0.1


# create volunteer and issue id card
# composer participant add --card admin@blockchain-network --data '{"$class":"at.jku.cis.Volunteer","firstName":"Philipp","lastName":"Starzer","email":"ps@mail.com"}'
# composer identity issue --card admin@blockchain-network --file volunteer1.card --newUserId volunteer1 --participantId 'resource:at.jku.cis.Volunteer#ps@mail.com'

# composer participant add --card admin@blockchain-network --data '{"$class":"at.jku.cis.Volunteer","firstName":"Berthold","lastName":"Roiser","email":"br@mail.com"}'
# composer identity issue --card admin@blockchain-network --file volunteer2.card --newUserId volunteer2 --participantId 'resource:at.jku.cis.Volunteer#br@mail.com'


# create organisation and issue id card
# composer participant add --card admin@blockchain-network --data '{"$class":"at.jku.cis.Organisation","orgName":"org1","email":"org1@mail.com"}'
# composer identity issue --card admin@blockchain-network --file organisation1.card --newUserId organisation1 --participantId 'resource:at.jku.cis.Organisation#org1@mail.com'

# create organisation and issue id card
# composer participant add --card admin@blockchain-network --data '{"$class":"at.jku.cis.Organisation","orgName":"org2","email":"org2@mail.com"}'
# composer identity issue --card admin@blockchain-network --file organisation2.card --newUserId organisation2 --participantId 'resource:at.jku.cis.Organisation#org2@mail.com'






















