#!/bin/bash
# init script for initializing blockchain-network with data

echo "INIT START"
~/fabric-tools/stopFabric.sh
~/fabric-tools/teardownFabric.sh

rm -rf $HOME/.composer

rm *.card
rm *.bna

# Starting the Fabric
~/fabric-tools/downloadFabric.sh
~/fabric-tools/startFabric.sh
~/fabric-tools/createPeerAdminCard.sh

# Deploying the business network
composer archive create -t dir -n .
composer runtime install --card PeerAdmin@hlfv1 --businessNetworkName blockchain-network
composer network start --card PeerAdmin@hlfv1 --networkAdmin admin --networkAdminEnrollSecret adminpw --archiveFile blockchain-network@0.0.1.bna --file blockchainadmin.card
composer card import --file blockchainadmin.card



# Register participants
composer participant add --card admin@blockchain-network --data '{"$class":"at.jku.cis.Volunteer","firstName":"Berthold","lastName":"Roiser","email":"br@mail.com"}'
composer identity issue --card admin@blockchain-network --file volunteer1.card --newUserId volunteer1 --participantId 'resource:at.jku.cis.Volunteer#br@mail.com'
composer card import --file volunteer1.card

composer participant add --card admin@blockchain-network --data '{"$class":"at.jku.cis.Volunteer","firstName":"Philipp","lastName":"Starzer","email":"ps@mail.com"}'
composer identity issue --card admin@blockchain-network --file volunteer2.card --newUserId volunteer2 --participantId 'resource:at.jku.cis.Volunteer#ps@mail.com'
composer card import --file volunteer2.card

composer participant add --card admin@blockchain-network --data '{"$class":"at.jku.cis.Volunteer","firstName":"Paul","lastName":"Mayr","email":"pm@mail.com"}'
composer identity issue --card admin@blockchain-network --file volunteer3.card --newUserId volunteer3 --participantId 'resource:at.jku.cis.Volunteer#pm@mail.com'
composer card import --file volunteer3.card

composer participant add --card admin@blockchain-network --data '{"$class":"at.jku.cis.Volunteer","firstName":"Franz","lastName":"Mueller","email":"fm@mail.com"}'
composer identity issue --card admin@blockchain-network --file volunteer4.card --newUserId volunteer4 --participantId 'resource:at.jku.cis.Volunteer#fm@mail.com'
composer card import --file volunteer4.card
#---

# Register organisations
composer participant add --card admin@blockchain-network --data '{"$class":"at.jku.cis.Organisation","orgName":"org1","email":"org1@mail.com"}'
composer identity issue --card admin@blockchain-network --file organisation1.card --newUserId organisation1 --participantId 'resource:at.jku.cis.Organisation#org1@mail.com'
composer card import --file organisation1.card

composer participant add --card admin@blockchain-network --data '{"$class":"at.jku.cis.Organisation","orgName":"org2","email":"org2@mail.com"}'
composer identity issue --card admin@blockchain-network --file organisation2.card --newUserId organisation2 --participantId 'resource:at.jku.cis.Organisation#org2@mail.com'
composer card import --file organisation2.card
#---

# Create tasks
echo "Create tasks"
composer transaction submit --card organisation1@blockchain-network --data '{"$class":"at.jku.cis.createTask","taskId": "a","description": "Textual description of task a","creator": "org1@mail.com"}'

composer transaction submit --card organisation1@blockchain-network --data '{"$class":"at.jku.cis.createTask","taskId": "b","description": "Textual description of task b","creator": "org1@mail.com"}'

composer transaction submit --card organisation2@blockchain-network --data '{"$class":"at.jku.cis.createTask","taskId": "c","description": "Textual description of task c","creator": "org2@mail.com"}'

composer transaction submit --card organisation2@blockchain-network --data '{"$class":"at.jku.cis.createTask","taskId": "d","description": "Textual description of task d","creator": "org2@mail.com"}'

composer transaction submit --card organisation1@blockchain-network --data '{"$class":"at.jku.cis.createTask","taskId": "e","description": "Textual description of task e","creator": "org1@mail.com"}'

composer transaction submit --card organisation1@blockchain-network --data '{"$class":"at.jku.cis.createTask","taskId": "f","description": "Textual description of task f","creator": "org1@mail.com"}'

composer transaction submit --card organisation2@blockchain-network --data '{"$class":"at.jku.cis.createTask","taskId": "g","description": "Textual description of task g","creator": "org2@mail.com"}'

composer transaction submit --card organisation2@blockchain-network --data '{"$class":"at.jku.cis.createTask","taskId": "h","description": "Textual description of task h","creator": "org2@mail.com"}'
#---

# Reserve tasks
echo "Reserve tasks"
composer transaction submit --card volunteer1@blockchain-network --data '{"$class":"at.jku.cis.reserveTask","task": "a","volunteer": "br@mail.com"}'
composer transaction submit --card volunteer2@blockchain-network --data '{"$class":"at.jku.cis.reserveTask","task": "a","volunteer": "ps@mail.com"}'

composer transaction submit --card volunteer1@blockchain-network --data '{"$class":"at.jku.cis.reserveTask","task": "b","volunteer": "br@mail.com"}'
composer transaction submit --card volunteer2@blockchain-network --data '{"$class":"at.jku.cis.reserveTask","task": "b","volunteer": "ps@mail.com"}'

composer transaction submit --card volunteer3@blockchain-network --data '{"$class":"at.jku.cis.reserveTask","task": "c","volunteer": "pm@mail.com"}'
composer transaction submit --card volunteer1@blockchain-network --data '{"$class":"at.jku.cis.reserveTask","task": "c","volunteer": "br@mail.com"}'

composer transaction submit --card volunteer4@blockchain-network --data '{"$class":"at.jku.cis.reserveTask","task": "d","volunteer": "fm@mail.com"}'
composer transaction submit --card volunteer2@blockchain-network --data '{"$class":"at.jku.cis.reserveTask","task": "d","volunteer": "ps@mail.com"}'

composer transaction submit --card volunteer2@blockchain-network --data '{"$class":"at.jku.cis.reserveTask","task": "e","volunteer": "ps@mail.com"}'

composer transaction submit --card volunteer4@blockchain-network --data '{"$class":"at.jku.cis.reserveTask","task": "f","volunteer": "fm@mail.com"}'
#---

# Assign tasks
echo "Assign tasks"
composer transaction submit --card organisation1@blockchain-network --data '{"$class":"at.jku.cis.assignTask","task": "a","taskPerformer": ["br@mail.com"]}'
composer transaction submit --card organisation2@blockchain-network --data '{"$class":"at.jku.cis.assignTask","task": "b","taskPerformer": ["ps@mail.com"]}'

composer transaction submit --card organisation1@blockchain-network --data '{"$class":"at.jku.cis.assignTask","task": "c","taskPerformer": ["pm@mail.com"]}'
composer transaction submit --card organisation2@blockchain-network --data '{"$class":"at.jku.cis.assignTask","task": "d","taskPerformer": ["fm@mail.com"]}'
#---

# Finish task
echo "Finish tasks"
composer transaction submit --card volunteer1@blockchain-network --data '{"$class":"at.jku.cis.finishTask","task": "a"}'
composer transaction submit --card volunteer2@blockchain-network --data '{"$class":"at.jku.cis.finishTask","task": "b"}'
#---


echo "INIT END"

# composer-rest-server -c admin@blockchain-network -n never -w true
















