#!/bin/bash

echo "INIT START"
docker rm -f composer-rest-server

~/fabric-tools/stopFabric.sh
~/fabric-tools/teardownFabric.sh

rm -rf $HOME/.composer

rm *.card
rm *.bna

# Starting the Fabric
~/fabric-tools/downloadFabric.sh
~/fabric-tools/startFabric.sh
~/fabric-tools/createPeerAdminCard.sh

# Deploying the business network
composer archive create -t dir -n .
composer runtime install --card PeerAdmin@hlfv1 --businessNetworkName ivolunteer-blockchain
composer network start --card PeerAdmin@hlfv1 --networkAdmin admin --networkAdminEnrollSecret adminpw --archiveFile ivolunteer-blockchain@0.0.1.bna --file blockchainadmin.card
composer card import --file blockchainadmin.card



